### ISSUE TITLE
Improve "record attendance" feature workflow

### ISSUE THREAD

**Issue by LucaBarco** [StefanoBergia/PULSeBS_Team5#10]
Good afternoon ,
first of all good job! I really like the interface and the whole application in general (colours, calendar interface, etc.)..

I'd like to notice a little thing: maybe it could be better to have the "record attendance" form not in a new page but in the same page of the calendar (for example you can show it inside a modal). This can make your application more useful and user-friendly, in my opinion.

**Comment by jackgorga** [comment]
Thank you for the feedback :)
