### ISSUE TITLE
Support Officer - Input validation on Schedule Changing

### ISSUE THREAD

**Issue by Nino-n** [StefanoBergia/PULSeBS_Team5#11]
Hello guys, first of all good job, I really loved your PULSeBS system, 
I have just some suggestion, it be nice to have input validation on the interface where the schedule is changed, i'm referring in particular to the change of time, during the presentation i noticed that three 0 could be inserted in the minutes, it would be better if just integer between 1 and 59 could be inserted.
Thank you and good job :)

**Comment by jackgorga** [comment]
Yes thank's :)
