### ISSUE TITLE
Schedule modification in support officer page

### ISSUE THREAD

**Issue by s269731** [StefanoBergia/PULSeBS_Team5#14]
Hello, my issue regards the interface of the support officer.
I think it would be better to give the possibility to change schedule for all the lectures of a course (maybe inserting a range of dates), and not for one lecture at a time. To do so a list view instead of a calendar one should be more appropriate.
For the rest, I want to congrat again with you for the very good job!
Best regards

**Comment by jackgorga** [comment]
Hi, thank you very much for the feedback. We understand the idea of lectures list, but we want to note that schedule already changes for ALL lectures from the selected one. Maybe we have been a little quick on that point during the demo :)
