### ISSUE TITLE
Adding text label identifying lecture's status

### ISSUE THREAD

**Issue by gabrielefantini** [StefanoBergia/PULSeBS_Team5#2]
## From a student perspective
Maybe you could add a text label that identifies the status of the lecture. It can be added in the bottom part of the lection instance in the calendar for example. I think it would be nice to have the text the same colour of the status represented.

**Comment by jackgorga** [comment]
Thank you for the feedback. We finally decided not to add the label you asked for matters of space and grapichs. We will study something better to retreive the same goal.
